### ISSUE TITLE
Dagger error

### ISSUE THREAD

**Issue by OrhanTozan** [RankoR/android-smart-rate#90]
`2020-12-22 15:49:41.452 529-529/com.hello247.app.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hello247.app.android.dev, PID: 529
    java.lang.NoClassDefFoundError: Failed resolution of: Ldagger/internal/Preconditions;
        at com.g2pdev.smartrate.di.DaggerRateComponent$Builder.rateModule(DaggerRateComponent.java:1)
        at com.g2pdev.smartrate.SmartRate.initDagger(SmartRate.kt:7)
        at com.g2pdev.smartrate.SmartRate.init(SmartRate.kt:5)
        at com.hello247.app.android.core.MyApplication.onCreate(MyApplication.kt:109)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "dagger.internal.Preconditions" on path: DexPathList[[zip file "/data/app/com.hello247.app.android.dev-xH6rNHdf9Ny_NcqiqXtw1g==/base.apk"],nativeLibraryDirectories=[/data/app/com.hello247.app.android.dev-xH6rNHdf9Ny_NcqiqXtw1g==/lib/x86, /data/app/com.hello247.app.android.dev-xH6rNHdf9Ny_NcqiqXtw1g==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.g2pdev.smartrate.di.DaggerRateComponent$Builder.rateModule(DaggerRateComponent.java:1) 
        at com.g2pdev.smartrate.SmartRate.initDagger(SmartRate.kt:7) 
        at com.g2pdev.smartrate.SmartRate.init(SmartRate.kt:5) 
        at com.hello247.app.android.core.MyApplication.onCreate(MyApplication.kt:109) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by RankoR** [comment]
It seems to be a compiler (or R8) issue
